### ISSUE TITLE
conda environment notes

### ISSUE THREAD

**Issue by xvazquezc** [carolzhou/multiPhATE2#15]
Hi,
I've been testing the program using a full conda installation and I ran into a few installation issues related to some of the dependencies and I thought it would be a good idea to report them.

**BLAST+:** by default the environment installed `blast=2.6.0` but the `makeblastdb` fails due to a `libssl.so.1.0.0`, which might be a package-specific. Solved by forcing the installation of a newer version `conda install "blast>2.6"`

**BioPython:** not sure if it's specific to my system but the Annotation script was given an error with `from Bio import SeqIO`. I tested other biopython packages with the same issue. Solved by installing it via `pip` in the same conda env.

**libiconv:** `transeq` failed when called by `phate_genomeSequence.py` due to missing library `libiconv.so.2`. Installed as `conda install libiconv` solved it.

Cheers,
Xabi

**Comment by carolzhou** [comment]
Thank you, Xabi. Yes, these are system-specific issues, and it is very
helpful of you to point them out. My testing is limited to the very few
platforms I have access to, so having knowledgeable users find these types
of issues is enormously helpful. I will add text to the readme for the
benefit of other users. Again, thank you for your contribution, and thank
you for using multiPhATE2. -Carol

**Comment by carolzhou** [comment]
May I ask what machine and operating system you are running multiPhATE2 on?

**Comment by xvazquezc** [comment]
Sure. It is a HPC server running CentOS 7. But I'm installing it on my own account for individual use/testing and with no modules loaded (to avoid any potential conflict with the conda-installed packages).

**Comment by carolzhou** [comment]
Thank you!
