### ISSUE TITLE
GeneMarkS - gmhmmp: error, on open file /heu_11.mod

### ISSUE THREAD

**Issue by BlackBee-270** [carolzhou/multiPhATE2#20]
Good afternoon

I hope you're well. I'm a student and I'm trying to execute your pipeline to annotate a few phages i was given for my research project. This is my first time using Linux and executing a pipeline, so please bear with me if my question seems a little silly.

I've managed to set up multiPhATE2 in a conda environment and all other gene callers are working. But there appears to be a problem with GeneMarkS when I attempt to test the pipeline using only GeneMarkS (see below)

phate_genecallPhage says, running GeneMarkS.
gmhmmp: error, on open file /heu_11.mod  
gmhmmp: error, on open file /heu_11.mod
Traceback (most recent call last):
File "/home/username/multiPhATE2/GeneCalling/phate_genecallPhage.py", line 470, in <module>
for line in open(outputFolder + 'geneMartkS.gff', 'rt'):
FileNotFoundError: [Errrno 2] No such file or directory: 'home/username/multiPhATE2/PipelineOutput/Eb_P2/geneMarkS.gff'
phate runPipeline says, Gene-call processing complete

I followed the installation instructions for GeneMarkS (copied the contents of the software distribution to my working directory in addition to depositing them into ~/anaconda3/envs/multiphate2/bin/ in an attempt to do a global install)

I tried to run GeneMarkS using the following command to test if it works
$ gmhmmp -m heu_11.mod sequence.fasta -o output1
and found that it is working correctly ->so I tried to rename my output as geneMarkS.gff and paste into the appropriate Pipeline Output Directory so that the genecalls could be included in the "superset.cgc" file along with Glimmer, Prodigal and Phanotate genecalls but found that did not work.

So at this point I'm just stuck, I was hoping that maybe you could walk me through how you installed GeneMarkS for multiPhATE2, because there might've been something I missed.

Any help you could offter would be greatly appreciated

**Comment by carolzhou** [comment]
Please send me your output files from GeneMarkS run at the command line.  You may send them via email to multiphate@gmail.com.

**Comment by BlackBee-270** [comment]
Email has been sent

**Comment by carolzhou** [comment]
I may need to make a few adjustments. Things change with respect to 3rd party codes and data sources.  It's likely I won't have this corrected today. If you are in a hurry, you can run GeneMarkS by hand, then format the gene calls as gff (like what Prodigal produces - see sample file, "Eb_P2.custom.gff") and input the file to multiPhATE2 as "custom".

**Comment by carolzhou** [comment]
What machine/OS are you running on?

**Comment by BlackBee-270** [comment]
I'm running on Ubuntu 18.04 64-bit. 

thank you so much for your help. i'll try the your second solution in the meantime

**Comment by carolzhou** [comment]
I have a code fix and will upload tomorrow morning, about 12 hours from
now. I was asking about your os because ... on a Mac I use, the security
control was not allowing genemarks to run at all. But most likely that will
not be an issue for you. Check back in 12 hours.

**Comment by carolzhou** [comment]
Please download revised code. Notice that in the configuration file you need to provide the location of your instance of GeneMarkS. For example, genemarks_path='/home/mydir/genemark_suite_macosx/gmsuite/'.  Let me know whether this solves the issue.

**Comment by BlackBee-270** [comment]
will do, thanks so much for your help

**Comment by BlackBee-270** [comment]
its working perfectly now. thank you for the fix

**Comment by carolzhou** [comment]
Great! Thank you for using multiPhATE2.
