### ISSUE TITLE
Can't get genemark to run

### ISSUE THREAD

**Issue by rfcohen** [carolzhou/multiPhATE2#22]
Trying to get gene mark running for gene calling.  I set the flag in the config file to true, but it produces no genemark output.

Where/how does one tell multiphate where the genemark installation is?

Again, love the tool.

Thx.

**Comment by carolzhou** [comment]
This has been repaired. Download the most recent code. Notice that the
sample.multiphate.config file is simplified and includes a parameter for
the location of your instance of genemarks. Let me know if this does not
solve the issue.

**Comment by rfcohen** [comment]
This helped a lot.  Still have some issues.  Needed to add -s and remove -r to make it work.  Thx.

**Comment by carolzhou** [comment]
? Where were the 's' and 'r'?

**Comment by rfcohen** [comment]
Original vs. my small change. (sorry about the bold, I don't know how to format it correctly)
`
systemCall(geneMarkSPath + 'gmhmmp -m ' + geneMarkSPath + '/heu_11.mod -s' + fastaFileName + ' -o ' + outputFolder + 'geneMarkS.lst')
    systemCall(geneMarkSPath + 'gmhmmp -m ' + geneMarkSPath + '/heu_11.mod -s' + fastaFileName + ' -o ' + outputFolder + 'geneMarkS.gff -f G')
#    systemCall(geneMarkSPath + 'gmhmmp -m ' + geneMarkSPath + '/heu_11.mod ' + fastaFileName + ' -o ' + outputFolder + 'geneMarkS.lst -r')
#    systemCall(geneMarkSPath + 'gmhmmp -m ' + geneMarkSPath + '/heu_11.mod ' + fastaFileName + ' -o ' + outputFolder + 'geneMarkS.gff -r -f G')
`

**Comment by rfcohen** [comment]
Ignore my previous note(s).  I have an older version of genemark.  I should be in better shape now.

**Comment by rfcohen** [comment]
Finally got it to run.  Thx.

**Comment by carolzhou** [comment]
Thank you for using multiPhATE2!
