### ISSUE TITLE
"consensus" parameter doesn't seem to work as intended

### ISSUE THREAD

**Issue by Calvinblue** [carolzhou/multiPhATE2#25]
Hello, 

I am testing multiphate2 and I used it using the consensus parameter for the gene calling step. However, some CDS in the consensus.cgc file were only detected by a single gene caller.

Can you please confirm that I have not made a mistake here ? Thanks in advance!

Best regards

[consensus.txt](https://github.com/carolzhou/multiPhATE2/files/6117324/consensus.txt)
[config.txt](https://github.com/carolzhou/multiPhATE2/files/6117325/config.txt)
[superset.txt](https://github.com/carolzhou/multiPhATE2/files/6117328/superset.txt)

**Comment by carolzhou** [comment]
Please also provide the CGC_results.txt file. Thank you.

**Comment by Calvinblue** [comment]
[CGC_results.txt](https://github.com/carolzhou/multiPhATE2/files/6118052/CGC_results.txt)

Here it is !

**Comment by carolzhou** [comment]
Some gene calls that did not belong in the consensus set were being printed to the consensus.cgc file. I believe that code has now been repaired; those calls are now being filtered out. Please let me know if the code does not perform as expected.

**Comment by Calvinblue** [comment]
I have tested it and I think it works now, thank you for your help !
