### ISSUE TITLE
Can't get annotation out of custom genecall

### ISSUE THREAD

**Issue by Calvinblue** [carolzhou/multiPhATE2#26]
Hello, 

I am trying to run multiPhATE2 on my computer, using the provided Eb_P2.fasta example but the program crashes because it can't find PipelineOutput/Eb_P2/custom.cgc, which I think it is not actually generating.
Could you please help me ? I have included the terminal input, config file, and PipelineOutput/Eb_P2

Thank you !
[multiphate_output.txt](https://github.com/carolzhou/multiPhATE2/files/6148669/multiphate_output.txt)
[Eb_P2.zip](https://github.com/carolzhou/multiPhATE2/files/6148681/Eb_P2.zip)
[test.multiPhate.config.txt](https://github.com/carolzhou/multiPhATE2/files/6148685/test.multiPhate.config.txt)

**Comment by carolzhou** [comment]
Please set custom_gene_calls to true in your config file. Let me know if
that does not solve the problem.

**Comment by Calvinblue** [comment]
Thank you for your help ! I don't know why I did not see the option, it was pretty obvious 😅
The program seems to run fine but I still get two errors (which do not prevent the ouptut of custom.cgc or the final gff file) : 

python multiPhate.py test.multiPhate.config
sh: /vog.gene.headers.lst: Read-only file system
sh: /vog.protein.headers.lst: Read-only file system
**multiPhate says, ERROR: unrecognized line in config file:**  
phate_runPipeline says, Checking files...
phate_runPipeline says, Configuration complete.
phate_runPipeline says, Preparing to run genecall module...
phate_runPipeline says, Calling the gene-call module.
phate_genecallPhage says, custom calls need to be converted to cgc format.
**ERROR in phate_genecallPhage.py, running Convert_gff2cgc(),**  /Users/antoine/multiPhATE2/PipelineOutput/Eb_P2/Eb_P2.custom.gff /Users/antoine/multiPhATE2/PipelineOutput/Eb_P2/custom.cgc

Raw Prodigal GFF :  
Raw Glimmer Output :  
Raw GeneMarkS GFF :  

CGC_parser says, Begin processing; gathering input parameters.
CGC_parser says, Checking files.
CGC_parser says, Parsing gene call outputs.
CGC_parser says, Processing complete.
phate_runPipeline says, Gene-call processing complete.
phate_runPipeline says, Preparing command strings for homology searches...
phate_runPipeline says, Calling the sequence annotation module.
phate_sequenceAnnotation_main says, Configuration complete for sequence annotation module.
phate_sequenceAnnotation_main says, Preparing for sequence annotation: setting parameters...
phate_sequenceAnnotation_main says, Running trnascan.
phate_trna says, Running setParameters.
phate_trna says, Running runTrnaScan.
phate_trna says, Running trnascan-se
phate_sequenceAnnotation_main says, trnascan execution complete.
phate_sequenceAnnotation_main says, Recording trna gene calls in genome object.
phate_sequenceAnnotation_main says, tRNA processing is complete.
phate_sequenceAnnotation_main says, Processing gene calls...
phate_sequenceAnnotation_main says, geneCallInfo {'primaryCalls': 'custom', 'primaryCallsPathFile': '/Users/antoine/multiPhATE2/PipelineOutput/Eb_P2/custom.cgc', 'genomeName': 'Eb_P2'} infile_primaryCalls /Users/antoine/multiPhATE2/PipelineOutput/Eb_P2/custom.cgc contigSeqLen_hash {'Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome': 33593}
Translate nucleic acid sequences
[...]
Translate nucleic acid sequences
phate_sequenceAnnotation_main says, Writing genes file
phate_sequenceAnnotation_main says, Writing peptides file
phate_sequenceAnnotation_main says, Gene and protein files created.
phate_sequenceAnnotation_main says, Preparing for blast...
phate_sequenceAnnotation_main says, Preparing to run blastp
phate_sequenceAnnotation_main says, Skipping genome blast
phate_sequenceAnnotation_main says, Skipping gene blast.
phate_sequenceAnnotation_main says, Skipping protein blast
phate_sequenceAnnotation_main says, Skipping HMM sequence search
phate_sequenceAnnotation_main says, Skipping HMM profile search.
phate_sequenceAnnotation_main says, Reporting final annotations
phate_genomeSequence says, There are 43 genes, 43 proteins, and 0 trna genes
phate_genomeSequence says, Writing data to GFF file.
phate_sequenceAnnotation_main says, Sequence annotation complete.
phate_runPipeline says, Sequence annotation processing is complete.
phate_runPipeline says, Code completed at 2021-03-16 14:26:34.603205
multiPhate says, Skipping CompareGeneProfiles.
multiPhate says, Skipping Genomics.

[Eb_P2.zip](https://github.com/carolzhou/multiPhATE2/files/6149313/Eb_P2.zip)

**Comment by carolzhou** [comment]
Thank you for finding these issues! Sometime things don't show up until one newly downloads the code and runs it without certain files already being in place. As you noticed, none of these issues were fatal errors, but the erroneous messages were pesky. I cleaned things up, and you should no longer see those ERROR messages, but please do let me know if you see anything else unexpected.

**Comment by Calvinblue** [comment]
Thank you 🙂
I launched yesterday (before your update) a heavier multiphate2 test with as all databases (except KEGG for which I don't have a license and CAZy for which i do not understand what the cazy_annotation_path='' variable refered to) on a HPC machine and I have some more errors that might be interesting to look at. It starts around line 231 of the .out.txt file (which is the terminal output).

[B_5.multiPhate.config.txt](https://github.com/carolzhou/multiPhATE2/files/6155572/B_5.multiPhate.config.txt)
[slurm-7227593.out.txt](https://github.com/carolzhou/multiPhATE2/files/6155574/slurm-7227593.out.txt)


- I get "Failed to open target sequence database NR_PATH for reading " error (and also with Refseq_PATH), which looks like a hmmscan error. I guess hmmscan is not supposed to search in refseq nor NR. It is also not an issue of database configuration in my understanding because blast manages to search these two databases as you can see later in the ouput

- I set the number of thread to 40 but multiphate says it first runs blast on Virus Genome database with 1 core, then checks how many cores are requested (40), then tells this amount of cores it is out of bonds and resets them to 10 cores, but continues using 1 core anyway. In my opinion, the 40 core maximum could be replaced by a warning for PC users.

- I get "WARNING: Unrecognized database: nr" and "WARNING: Unrecognized database: swissprot" errors despite having the databases properly installed (and md5 checked), the error also does not prevent the final gff output. Interestingly, this warning doesn't occur at every blast occurence on swissprot or NR.

**Comment by carolzhou** [comment]
HMM search uses sequence databases. Normally users download only the
blast-formatted databases for NR and refseq-protein because the sequence
databases are so large. So unless you have the actual sequence databases,
the hmm searches cannot run.

The numbers of PhATE threads and CGP threads are limited based on the
number of genomes. If you have N genomes, then the maximum number of
threads (processors, actually) will be N for PhATE processing, and the
number for CGP will be N(N-1)/2. These limits are calculated and imposed my
multiphate2. The number of blast threads you may choose is unlimited, but
selecting no more than 4 is recommended, else blast will thrash. HMM
searches do not have a multithreaded option that I am aware of and was not
implemented in multiphate2.  MultiPhATE2 uses multiprocessing in an
"embarrassingly parallel" manner. In other words, the numbers of processors
allowed are one per instance of PhATE, and one per binary genome comparison
in CGP. Therefore, it is feasible to run on HPC if you have many genomes,
but running one genome on HPC provides no advantage.

Swissprot has been an ongoing issue. Blast has difficulty identifying
Swissprot. I found that only the version of swissprot downloaded from
Uniprot can be recognised by blast+ installed using conda. This is not a
multiphate problem. This one is on blast. First try downloading your
swiaaprot database from Uniprot. Also try formatting the sequence database
by hand with makeblastdb. If that doesn't work, then try downloading blast+
from a different source.

I hope this all helps. The Troubleshooting section of the README might
provide more information about these issues.

**Comment by carolzhou** [comment]
For CAZy you need to provide the locations of the database proper and its
associated annotation file, both downloaded from CAZy. The phate-getDBs
script should download these for you.

**Comment by Calvinblue** [comment]
Thank you for those explanations, it's much clearer. Could you please elaborate on the subject of the recommended maximum of blast threads ? Are the alignment results changed ? Or is it that blast is limited by RAM and/or data I/O past that 4 threads threshold ?

**Comment by carolzhou** [comment]
Blast threads share the memory on a given processor. If the fixed memory is
split too many ways, then it results in thrashing, which means that each
tgread does not have enough memory to do its work without waiting for
memory to become available. How many threads you can reasonably request for
blast is system dependent, but four is generally a good starting point. In
the testing I did on the cluster I use, asking for more than ten blast
threads made blast run slower than if I selected one.

**Comment by Calvinblue** [comment]
So if my understanding is correct : if too many blast threads are used, they each get a small fraction of the memory allocated to the job, which slows the overall process. But if the the node the job is ran on has enough memory, it is possible to increase the number of threads ?

**Comment by carolzhou** [comment]
Yes. You can experiment with that. Too many threads, and blast might fail.
Maybe it will depend on your data sets too, so don't think that there is a
fixed optimum.

**Comment by Calvinblue** [comment]
Ok. Thank you again for those kind explanations !
