### ISSUE TITLE
 sample.multiPhate.config 

### ISSUE THREAD

**Issue by smeeta** [carolzhou/multiPhATE2#27]
Dear Carol Zhou , 

I am trying to run the multiPhATE2 . I get the following error.

If I understand the tutorial- I just need to change few parameters in the config file. 

-  phanotate_calls='true' - genemarks_calls='false' - prodigal_calls='true' - glimmer_calls='true'
- blastp='true' - pvogs_blast='true' - phantome_blast='true' 
- phantome_database_path='$HOME/multiphate2/multiPhATE2/Databases/Phantome'
- pvogs_database_path='$HOME/multiphate2/multiPhATE2/Databases/pVOGs'

However I get this error.

(multiphate2) smeetas-MacBook-Air:multiPhATE2-master smeeta$ python3 multiPhate.py sample.multiPhate.config
sh: /vog.gene.headers.lst: Permission denied
sh: /vog.protein.headers.lst: Permission denied
multiPhate says, ERROR: unrecognized line in config file:  
multiPhate says, ERROR: Cannot verify blast database for  /Databases/pVOGs  Please check your configuration file and Databases/ directory.

Thank you so much.
regards
Smeeta

**Comment by carolzhou** [comment]
I suggest providing the complete path to your databases, rather than using $HOME.  The other errors are non-fatal, and should be gone in version 2.02 of multiPhATE2. Please download the most recent version.

**Comment by carolzhou** [comment]
Try adding to your database paths:  /Phantome_Phage_genes.faa, and /pVOGs.faa.

**Comment by smeeta** [comment]
Thank you. I have downloaded the latest version : multiPhATE v.2.0.2
I will try the other suggestions.

**Comment by carolzhou** [comment]
Let me know if you have any other issues. Thank you for your interest in multiPhATE2.
