### ISSUE TITLE
How to annotate the gene name to the ORF output from multiPhATE2 

### ISSUE THREAD

**Issue by smeeta** [carolzhou/multiPhATE2#28]
Hi Carol,

I managed to run multiPhATE2 for the test fasta files which was there in the file eg Eb_P2 and Eb_Wphi.

However in PipelineOutput file i get results like below but no annotations are provided. How do I annotate the ORFs ?

orf00001        187     1221    -       8.95    glimmer3        Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome
orf00003        1221    3023    -       13.44   glimmer3        Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome
orf00004        3101    4021    +       15.05   glimmer3        Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome
orf00005        4080    5153    +       14.21   glimmer3        Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome
orf00007        5157    5900    +       15.30   glimmer3        Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome
orf00008        5940    6509    +       12.24   glimmer3        Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome
orf00009        6509    6712    +       6.63    glimmer3        Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome
orf00011        6716    6997    +       9.55    glimmer3        Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome
orf00013        6997    7494    +       11.72   glimmer3        Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome

**Comment by carolzhou** [comment]
Please provide your configuration file.

**Comment by smeeta** [comment]
Please find attached my .config file.

[multiPhate.config.pdf](https://github.com/carolzhou/multiPhATE2/files/6215015/multiPhate.config.pdf)



I read from link : issue 10 the following : 

Issue 10: The VOG Genes or VOG Proteins database is not returning meaningful annotations. Try this: Be sure that you are using the vog.genes.tagged.all.fa or vog.proteins.tagges.all.faa database. These "tagged" databases are computed using the dbPrep_getDBs.py script. This is necessary, because the original VOG fasta databases do not include the VOG identifiers in the headers. The dbPrep_getDBs.py script pulls the VOG identifier(s) for each fasta sequence and re-writes the header accordingly. Then, with these modified headers, multiPhATE2's blastn or blastp process can readily look up the annotation using the VOG identifier(s). The pre-processing can be done by hand using scripts in the DatabasePrep/ folder, but it is strongly recommended to use the option(s) available in dbPrep_getDBs.py.


I did run dbPrep_getDBs.py but I realised that my files have not changed into tagged forms ie 
I still have "vog.genes.all.fa.gz" which should have changed to "vog.genes.tagged.all.fa".

Thank you so much.

**Comment by carolzhou** [comment]
Your configuration file looks fine. Please let me know whether the code is
generating the phate_sequenceAnnotation_main.out and .gff files under the
Eb_P2 subdirectory. If so, it would be helpful to see the contents of one
or the other.

Regarding the tagged vog data, I will test the  getDBs script to verify
whether there may have been any changes at the vog source. Stay tuned.

**Comment by smeeta** [comment]
Yes, I have phate_sequenceAnnotation_main.out and .gff files under the Eb_P2 subdirectory  but both are empty.

Mean time I am trying to use the  dbPrep_getDBs.py script  to convert my "vog.genes.all.fa.gz"  to "vog.genes.tagged.all.fa".

**Comment by carolzhou** [comment]
Let's start small and be sure that the phate_sequenceAnnotation_main files
can be written with correct data. I suggest you run a single gene caller,
turn to false the ncbi virus genomes, turn to false the vog genes, and run
blastp only with the PHANTOME database as true. Let me know if you see any
error messages.

**Comment by smeeta** [comment]
Hi Carol,

**I did as suggested I just used one caller :**  

phanotate_calls='true'
prodigal_calls='false'
glimmer_calls='false'
genemarks_calls='false'
genemarks_path=''
custom_gene_calls='false'
primary_calls='phanotate'

ncbi_virus_genome_blast='false'
vog_gene_blast='false'
blastp='true'

(multiphate2) smeetas-MacBook-Air:Eb_P2 smeeta$ ls -l
total 2752
drwxr-xr-x  5 smeeta  staff     160 Mar 30 17:28 BLAST
-rw-r--r--  1 smeeta  staff   80717 Mar 25 23:23 CGC_main.log
-rw-r--r--  1 smeeta  staff      20 Mar 30 17:28 CGC_parser.log
-rw-r--r--  1 smeeta  staff       0 Mar 30 17:28 CGC_parser.out
-rw-r--r--  1 smeeta  staff       0 Mar 30 17:28 CGC_parser.tmp
-rw-r--r--@ 1 smeeta  staff   39524 Mar 25 23:23 CGC_results.txt
-rw-r--r--  1 smeeta  staff       0 Mar 25 23:23 CGCcallSummary.gff
-rw-r--r--  1 smeeta  staff    1804 Mar 30 17:28 Eb_P2.json
-rw-r--r--  1 smeeta  staff   33142 Mar 30 17:28 Eb_P2_cgp_gene.fnt
-rw-r--r--  1 smeeta  staff   11437 Mar 30 17:28 Eb_P2_cgp_protein.faa
-rw-r--r--  1 smeeta  staff    3031 Mar 25 23:23 commoncore.cgc
-rw-r--r--  1 smeeta  staff    4740 Mar 25 23:23 consensus.cgc
-rw-r--r--  1 smeeta  staff   36161 Mar 30 17:28 gene.fnt
-rw-r--r--  1 smeeta  staff    3941 Mar 25 23:23 glimmer.cgc
-rw-r--r--  1 smeeta  staff    1720 Mar 25 23:22 glimmer.coords
-rw-r--r--  1 smeeta  staff   23653 Mar 25 23:22 glimmer.detail
-rw-r--r--@ 1 smeeta  staff  548924 Mar 25 23:22 glimmer.icm
-rw-r--r--  1 smeeta  staff     714 Mar 25 23:22 glimmer.longorfs
-rw-r--r--  1 smeeta  staff    1780 Mar 25 23:22 glimmer.predict
-rw-r--r--  1 smeeta  staff   20508 Mar 25 23:22 glimmer.train
-rw-r--r--  1 smeeta  staff    4474 Mar 30 17:28 phanotate.cgc
-rw-r--r--  1 smeeta  staff    5213 Mar 30 17:28 phanotateOutput.txt
-rw-r--r--  1 smeeta  staff    2770 Mar 30 17:28 phate_genecallPhage.log
-rw-r--r--  1 smeeta  staff    3810 Mar 25 23:23 phate_glimmer.gff
-rw-r--r--  1 smeeta  staff    4445 Mar 30 17:28 phate_phanotate.gff
-rw-r--r--  1 smeeta  staff    3850 Mar 25 23:23 phate_prodigal.gff
-rw-r--r--  1 smeeta  staff   42520 Mar 30 17:30 phate_sequenceAnnotation_main.gff
-rw-r--r--  1 smeeta  staff    4283 Mar 30 17:30 phate_sequenceAnnotation_main.log
-rw-r--r--  1 smeeta  staff   99540 Mar 30 17:30 phate_sequenceAnnotation_main.out
-rw-r--r--  1 smeeta  staff    3939 Mar 25 23:23 prodigal.cgc
-rw-r--r--  1 smeeta  staff   98504 Mar 25 23:22 prodigal.genes.potential
-rw-r--r--  1 smeeta  staff     982 Mar 25 23:22 prodigal.genes.sco
-rw-r--r--  1 smeeta  staff   11959 Mar 25 23:22 prodigal.gff
-rw-r--r--  1 smeeta  staff   38841 Mar 25 23:22 prodigal.proteins.faa
-rw-r--r--  1 smeeta  staff   14710 Mar 30 17:28 protein.faa
-rw-r--r--@ 1 smeeta  staff    4372 Mar 30 17:28 results.txt
-rw-r--r--  1 smeeta  staff    4329 Mar 30 17:30 runPhATE.log
-rw-r--r--  1 smeeta  staff    5676 Mar 25 23:23 superset.cgc
-rw-r--r--  1 smeeta  staff     296 Mar 30 17:28 tempGeneFile
-rw-r--r--  1 smeeta  staff     157 Mar 30 17:28 tempProtFile
-rw-r--r--  1 smeeta  staff       0 Mar 25 23:23 trnaGenes.out
-rw-r--r--  1 smeeta  staff    3912 Mar 25 23:23 trnaStatistics.out
-rw-r--r--  1 smeeta  staff       0 Mar 25 23:23 trnaStructures.out



**when I view the file : phate_sequenceAnnotation_main.out** 


I get this : 

Genome:Eb_P2    Name:unknown    Type:phage
Contigs:1       Genes:49        Proteins:49     Annotations:152
Header:Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome       Name:none       Type:nt Order:1 parent:0/0//    length: 33593
There are no annotations
Sequence too long to print. See file.
Header:Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome_phanotate_1_geneCall  Name:none       Type:nt Order:1 parent:187/1221/-/Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome    length: 1035
There are no annotations
Sequence too long to print. See file.
Header:Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome_phanotate_2_geneCall  Name:none       Type:nt Order:2 parent:1221/2993/-/Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome   length: 1773
There are no annotations
Sequence too long to print. See file.
Header:Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome_phanotate_3_geneCall  Name:none       Type:nt Order:3 parent:3101/4021/+/Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome   length: 921
There are no annotations
atgcgcatcgtcgggaaactgatgccgacatgtgactcctctaatcactattcaggactcctgacaatggcaaaaaaagtctcaaaattctttcgtatcggcgttgagggtgacacctgtgacgggcgtgtcatcagtgcgcaggatattcaggaaatggccgaaacctttgacccgcgtgtctatggttgccgcattaacctggaacatctgcgcggcatcctgcctgacggtatttttaagcgttatggcgatgtggccgaactgaaggccgaaaagattgacgatgattcggcgctgaaaggcaaatgggcgctgtttgcgaaaatcaccccgaccgatgaccttatcgcgatgaacaaggccgcgcagaaggtctacacctcaatggaaattcagccgaactttgccaacaccggcaaatgttatctggtgggtctggccgtcaccgatgacccggcaagcctcggcacggaatacctggaattctgccgcacggcaaaacacaaccccctgaaccgcttcaaattaagccctgaaaacctgatttcagtggcaacgcctgttgagctggaatttgaagacctgcctgaaaccgtgttcaccgccctgaccgaaaaggtgaagtccatttttggccgcaaacaggccagcgatgatgcccgtctgaatgacgtgcatgaagcggtgaccgctgttgctgaacatgtgcaggaaaaactgagcgccactgagcagcgcctcgctgagatggaaaccgccttttctgcacttaagcaggaggtgactgacagggcggatgaaaccagccaggcattcacccgcctgaaaaacagtctcgaccacaccgaaagtctgacccagcagcgccgcagcaaagccaccggcggtggcggtgacgccctgatgacgaactgctga
Header:Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome_phanotate_4_geneCall  Name:none       Type:nt Order:4 parent:4080/5153/+/Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome   length: 1074
There are no annotations
Sequence too long to print. See file.
Header:Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome_phanotate_5_geneCall  Name:none       Type:nt Order:5 parent:5157/5900/+/Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome   length: 744
There are no annotations

****Also in viewing phate_sequenceAnnotation_main.gff I get the following :**** 


Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome      PhATE   gene    187     1221    .       -       .       ID=Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome_phanotate_1_geneCall
Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome      PhATE   CDS     187     1221    .       -       .       ID=Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome_phanotate_1_geneCall_cds; annot1=(homology - blastp) fig|10679.1.peg.1 [Phage capsid protein # ACLAME 81] [ACLAME_Phage_head Phage_capsid_proteins] [10679.1] [Enterobacteria phage P2] ; annot2=(homology - blastp) fig|227940.1.peg.1 [Phage capsid protein # ACLAME 81] [ACLAME_Phage_head Phage_capsid_proteins] [227940.1] [Bacteriophage L-413C] ; annot3=(homology - blastp) fig|103216.1.peg.1 [Phage capsid protein # ACLAME 81] [ACLAME_Phage_head Phage_capsid_proteins] [103216.1] [Bacteriophage WPhi] ; annot4=(homology - blastp) fig|1357825.3.peg.1 [capsid portal protein] [Not in a subsystem] [1357825.3] [Enterobacteria phage fiAA91-ss, complete genome.]
Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome      PhATE   gene    1221    2993    .       -       .       ID=Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome_phanotate_2_geneCall
Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome      PhATE   CDS     1221    2993    .       -       .       ID=Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome_phanotate_2_geneCall_cds; annot1=(homology - blastp) fig|10679.1.peg.2 [Phage terminase, large subunit] [ACLAME_Phage_head Phage_packaging_machinery T4-like_phage_core_proteins zzRobE_test] [10679.1] [Enterobacteria phage P2] ; annot2=(homology - blastp) fig|1357825.3.peg.2 [large terminase subunit] [Not in a subsystem] [1357825.3] [Enterobacteria phage fiAA91-ss, complete genome.] ; annot3=(homology - blastp) fig|103216.1.peg.2 [Phage terminase, large subunit] [ACLAME_Phage_head Phage_packaging_machinery T4-like_phage_core_proteins zzRobE_test] [103216.1] [Bacteriophage WPhi] ; annot4=(homology - blastp) fig|227940.1.peg.2 [Phage terminase, large subunit] [ACLAME_Phage_head Phage_packaging_machinery T4-like_phage_core_proteins zzRobE_test] [227940.1] [Bacteriophage L-413C] ; annot5=(homology - blastp) fig|1173769.3.peg.2 [terminase ATPase subunit] [Not in a subsystem] [1173769.3] [Salmonella phage FSL SP-004, complete genome.]
Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome      PhATE   gene    3101    4021    .       +       .       ID=Eb_P2_NC_001895_1_Enterobacteria_phage_P2__complete_genome_phanotate_3_geneCall



Could you send me a snap shot as how ORF annotated output looks like ?

thank you.

**Comment by carolzhou** [comment]
You have annotations! The gff file shows them in column 9. In the .out file
you need to scroll down to see the protein-level annotations.

Now we need to fix your vog database(s).

**Comment by smeeta** [comment]
Yes I noted. It stated as follows - Phage capsid protein # ACLAME 81 , Phage terminase, large subunit, Phage capsid scaffolding protein , Phage major capsid protein, Phage terminase, small subunit
But no gene names are provided. 
Also thank you will wait for the vog database.

**Comment by carolzhou** [comment]
The annotations are what are reported in the databases. Gene names are
either assigned by expert curators, or copied from existing annotations in
the databases. You will see gene names most commonly for bacterial genes
when there are hits to well annotated genomes, such as E. coli or other
well-studied human pathogens. Do not expect that for bacteriophage.

**Comment by carolzhou** [comment]
The database download code was importing a module that has now become deprecated. I fixed that and am running a test download/formatting of the VOGs. The formatting takes several hours.  I'll let you know when the modified/tested script is uploaded to the repository.

**Comment by smeeta** [comment]
Thank you. Will wait for that. So just to confirm you are  correcting the dbPrep_getDBs.py script so that we can  convert "vog.genes.all.fa.gz" to "vog.genes.tagged.all.fa". ?

**Comment by carolzhou** [comment]
Not exactly. dbPrep_getDBs.py downloads the databases and formats the ones
that need formatting. The generation of the tagged vog databases is one of
the formatting operations. That script is subject to failure any time a
source changes something, like its URL or the name of its database--things
I don't control. In this case, a programming module written by others was
deprecated (ie, phased out) recently, so when dbPrep_getDBs tried to import
the module, the code failed. As you can see, codes need to be maintained,
as things change.

**Comment by smeeta** [comment]
Yes , I understand since looking into the dbPrep_getDBs.py script there are many source links which will change and one cannot be sure of it. I noted that there are many blanks in the annotation of the phage orf, this could be novel sequences which have no identified function/annotation due to which it is kept blank. I also noted that the multiphATE uses numerous databases to annotate, any suggestions which databases integration post gene call would give me a more complete annotation without hypothetical proteins or blanks ?. Apologies if some questions appear naive. I am more into human genome (UCSC genome browser) and viral and bacterial genomes are new to me.

**Comment by carolzhou** [comment]
For bacteriophage the best databases are Phantome, Vog gene and protein,
and CAZy. Run these at 60% sequence identity. You may use blast and one of
the hmm search algorithms. This should help you identify many of the phage
genes. For the unknown hypotheticals, add other databases and lower the
identity cutoff.  But remember that identity below about 30% is
meaningless. But you might be able to identify some functional domains.

Regarding gene calling, Phanotate is the most reliable, though it will call
more short genes that are unknown hypothetical. That does not necessarily
mean they are not real. Bacteriophage are highly diverse and the databases
are incomplete. Much is not known. You can compare gene callers in
CGC_results. txt.

I uploaded a repaired version of dbPrep_getDBs.py and a module,
dbPrep_fastaSequence.py. It correctly computed the gene tagged vog
database, but the protein is still running in my test. Very slow
computations on the machine I am using right now. Go ahead and give the
repaired code a try. Yours might finish faster than mine. Gene calculations
took 17 hours! But its a one-time computation.

**Comment by carolzhou** [comment]
The dbPrep_getDBs.py (and dbPrep_fastaSequence.py) code should be working again. Please download and give it a try.

**Comment by smeeta** [comment]
Sure will do that and revert.Thank you Carol !

**Comment by carolzhou** [comment]
Thank you for your interest in multiPhATE, Smeeta. Let me know if you encounter any other issues.
