### ISSUE TITLE
my genome contains zero length ?

### ISSUE THREAD

**Issue by smeeta** [carolzhou/multiPhATE2#29]
CGC_parser says, Begin processing; gathering input parameters.
CGC_parser says, Checking files.
CGC_parser says, Parsing gene call outputs.
CGC_parser says, Processing complete.
phate_runPipeline says, Gene-call processing complete.
phate_runPipeline says, Preparing command strings for homology searches...
phate_runPipeline says, Calling the sequence annotation module.
phate_sequenceAnnotation_main says, Configuration complete for sequence annotation module.
phate_sequenceAnnotation_main says, Preparing for sequence annotation: setting parameters...
phate_sequenceAnnotation_main says, Running trnascan.
phate_trna says, Running setParameters.
phate_trna says, Running runTrnaScan.
phate_trna says, Running trnascan-se
phate_sequenceAnnotation_main says, trnascan execution complete.
phate_sequenceAnnotation_main says, Recording trna gene calls in genome object.
phate_sequenceAnnotation_main says, tRNA processing is complete.
phate_sequenceAnnotation_main says, Processing gene calls...
**_phate_sequenceAnnotation_main says, geneCallInfo {'primaryCalls': 'phanotate', 'primaryCallsPathFile': '/Users/smeeta/myMultiphateDir/multiPhATE2-master/PipelineOutput/genome2/phanotate.cgc', 'genomeName': 'genome2'} infile_primaryCalls /Users/smeeta/myMultiphateDir/multiPhATE2-master/PipelineOutput/genome2/phanotate.cgc contigSeqLen_hash {'GU1962771_Escherichia_phage_K1G,_complete_genome': 43587}
Translate nucleic acid sequences
Warning: Sequence 'fasta::/Users/smeeta/myMultiphateDir/multiPhATE2-master/PipelineOutput/genome2/tempGeneFile:GU196277.1_phanotate_1_geneCall' has zero length, ignored
**Error:** Unable to read sequence '/Users/smeeta/myMultiphateDir/multiPhATE2-master/PipelineOutput/genome2/tempGeneFile'
Died: transeq terminated: Bad value for '-sequence' and no prompt
[sequence.fasta.txt](https://github.com/carolzhou/multiPhATE2/files/6289977/sequence.fasta.txt)

_**
Traceback (most recent call last):
  File "/Users/smeeta/myMultiphateDir/multiPhATE2-master/SequenceAnnotation/phate_sequenceAnnotation_main.py", line 1038, in <module>
    myGenome.processGeneCalls(geneCallInfo,PRIMARY_CALLS_FILE_H)
  File "/Users/smeeta/myMultiphateDir/multiPhATE2-master/SequenceAnnotation/phate_genomeSequence.py", line 413, in processGeneCalls
    newProtein.sequence = self.translateGene(newGene)
  File "/Users/smeeta/myMultiphateDir/multiPhATE2-master/SequenceAnnotation/phate_genomeSequence.py", line 731, in translateGene
    PROT_H = open(tempProtFile,"r")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/smeeta/myMultiphateDir/multiPhATE2-master/PipelineOutput/genome2/tempProtFile'
phate_runPipeline says, Sequence annotation processing is complete.
phate_runPipeline says, Code completed at 2021-04-10 22:02:43.945389
phate_runPipeline says, Checking files...
phate_runPipeline says, Configuration complete.
phate_runPipeline says, Preparing to run genecall module...
phate_runPipeline says, Calling the gene-call module.
phate_genecallPhage says, running Phanotate.

Please find attached genome2.fasta file

**Comment by smeeta** [comment]
My output file for genome2 looks like this :

(multiphate2) smeetas-MacBook-Air:genome2 smeeta$ ls -l
total 104
-rw-r--r--  1 smeeta  staff    20 Apr 10 22:02 CGC_parser.log
-rw-r--r--  1 smeeta  staff     0 Apr 10 22:02 CGC_parser.out
-rw-r--r--  1 smeeta  staff     0 Apr 10 22:02 CGC_parser.tmp
-rw-r--r--  1 smeeta  staff  1810 Apr 10 22:02 genome2.json
-rw-r--r--  1 smeeta  staff  3320 Apr 10 22:02 phanotate.cgc
-rw-r--r--  1 smeeta  staff  4522 Apr 10 22:12 phanotateOutput.txt
-rw-r--r--  1 smeeta  staff  2810 Apr 10 22:02 phate_genecallPhage.log
-rw-r--r--  1 smeeta  staff  3379 Apr 10 22:02 phate_phanotate.gff
-rw-r--r--  1 smeeta  staff     0 Apr 10 22:02 phate_sequenceAnnotation_main.gff
-rw-r--r--  1 smeeta  staff  3410 Apr 10 22:02 phate_sequenceAnnotation_main.log
-rw-r--r--  1 smeeta  staff     0 Apr 10 22:13 phate_sequenceAnnotation_main.out
-rw-r--r--  1 smeeta  staff  3246 Apr 10 22:02 results.txt
-rw-r--r--  1 smeeta  staff  4390 Apr 10 22:02 runPhATE.log
-rw-r--r--  1 smeeta  staff    34 Apr 10 22:02 tempGeneFile
-rw-r--r--  1 smeeta  staff     0 Apr 10 22:02 trnaGenes.out
-rw-r--r--  1 smeeta  staff  3920 Apr 10 22:02 trnaStatistics.out
-rw-r--r--  1 smeeta  staff     0 Apr 10 22:02 trnaStructures.out

**Comment by carolzhou** [comment]
Run your genome sequence through script cleanHeaders.py in the Utilities/ folder.  For example, $ python3 cleanHeaders.py sequence.fasta.txt > cleanSequence.fasta.txt.  This will remove non-alpha-numeric characters from the header. Some third-party codes do not handle non-alpha-numerics well. It is safest to remove them.

**Comment by carolzhou** [comment]
I think the non-alphanumeric characters in your fasta file header are causing the failure. If the above fix does not work, then feel free to re-open this issue. Thank you for your interest in multiPhATE2.
