### ISSUE TITLE
how long is "a while" for VOG installation using dbPrep_getDBs.py ? 

### ISSUE THREAD

**Issue by Calvinblue** [carolzhou/multiPhATE2#32]
I am updating the databases of multiPhate2 on a computer than handled the task without issue a few month ago, I haven't changed the conda env in wich multiphate2 runs. However, the script has been stuck at "dbPrep_vog says, Linking fastas to VOGs. Please be patient. This may take a while..." for 3 hours. Is it normal? 

Thank you four your help !

<img width="777" alt="Capture d’écran 2021-06-07 à 19 33 37" src="https://user-images.githubusercontent.com/52562847/121064236-98265380-c7c7-11eb-91fa-67cab82addda.png">

**Comment by carolzhou** [comment]
Yes, it is a very slow process to link each fasta to its annotations. The
good news is that you only have to do this one time to produce the
annotated fasta database, and when running multiphate the processing is
much faster because the annotations were all linked ahead of time.

**Comment by Calvinblue** [comment]
Thank you :) 
It took 3h40 for the first step to complete (out of 3)

Best,

Antoine
