### ISSUE TITLE
Can't Find GFF Output Files

### ISSUE THREAD

**Issue by joshuakirsch** [carolzhou/multiPhATE2#36]
Hi, I am trying to generate GFF files for my phage genomes with this tool but I cannot find the output files. I've included the log file here:
[multiPhate.log](https://github.com/carolzhou/multiPhATE2/files/7269807/multiPhate.log)

**Comment by carolzhou** [comment]
Multiphate is flagging a problem with your input genome files. Please post them here or send via email to multiphate@gmail.com.

**Comment by joshuakirsch** [comment]
[id_AB712291.txt](https://github.com/carolzhou/multiPhATE2/files/7269910/id_AB712291.txt)
I've uploaded this as a .txt but I switched the extension to .fa for multiphate

**Comment by carolzhou** [comment]
Use extension '.fasta' on your genome sequence files, and then let me know if that solves the problem.

**Comment by joshuakirsch** [comment]
I think it's working now! Thanks for the help!
