### ISSUE TITLE
Running VOGs hmm/profile search

### ISSUE THREAD

**Issue by LeonardoMorenoG** [carolzhou/multiPhATE2#37]
Hi! It's my first time trying to use multiphate2. Unfortunately, I'm getting the following error:
FileNotFoundError: [Errno 2] No such file or directory: '/vog.annotations.tsv'
I'm giving the absolute path of the database in the config file (e.g. vogs_hmm_profiles_database_path='myPath/multiPhATE2/Databases/VOGhmms/VOGsHmmProfilesDB.hmm'

When check_databases is true, no warning or error is printed. 

I hope you can help me!

**Comment by LeonardoMorenoG** [comment]
If the path to the file vog.annotations.tsv is specified as the "vog_protein_database_path" in the config file, there is no error.
Also if the file is configured to also blast VOGs, there is no error. 
Meaning that is "not possible" or "is not expected" to only run an HMMscan to VOGs. 

P.S. The same happens for pVOGs

**Comment by carolzhou** [comment]
I think the issue is that you need to include the vog.annotations.tsv file regardless of which analysis (blast, hmmscan) you are doing. Let me know if that does not clarify the usage.

**Comment by LeonardoMorenoG** [comment]
Ok... sorry, but what is the proper way to include the vog.annotations.tsv file?

**Comment by carolzhou** [comment]
Place the vog.annotations.tsv file in the same directory as the VOG database file(s).
