### ISSUE TITLE
Support json format for input config file

### ISSUE THREAD

**Issue by ilyavs** [carolzhou/multiPhATE2#38]
Hi,
For easier automation, it would be great if the input config file could be formatted as a json file. The current input config is nice to edit manually but is hard to edit with wrapping code.
Thanks,
Ilya.

**Comment by carolzhou** [comment]
A JSON input file could reasonably be added as an option for automated
processing. I would not want a human constructing a JSON file as there are
too many pitfalls. I appreciate your suggestion.

**Comment by ilyavs** [comment]
Thank you. I see the issue was closed as completed. Were the changes committed?

**Comment by carolzhou** [comment]
A simple parser could be constructed to convert a JSON file structured according to your choosing to the MultiPhATE2 user-friendly input file. If you would like to write such a script, I would be happy to include it in the distribution.
