### ISSUE TITLE
How to get the faa file for the superset gff?

### ISSUE THREAD

**Issue by ilyavs** [carolzhou/multiPhATE2#39]
Hi,
I am running multiphate2 with `primary_calls = 'superset'` (prodigal, phanotate and glimmer callers. Aiming to get the most comprehensive set of genes) and want to obtain both the gff and faa files. I assume the gff file is `phate_sequenceAnnotation_main.gff`. How can I get the corresponding faa file?
Thanks,
Ilya.

**Comment by carolzhou** [comment]
Look for the output files, protein.faa and gene.fnt.

**Comment by ilyavs** [comment]
Both protein.faa and gene.fnt contain fewer records than phate_sequenceAnnotation_main.gff. I ran this on the sample input data for Eb_P2.

**Comment by ilyavs** [comment]
Got it, thanks.
