### ISSUE TITLE
NCBI Virus and Protein Errors

### ISSUE THREAD

**Issue by lexikazen** [carolzhou/multiPhATE2#40]
<img width="468" alt="errorNCBIdownload" src="https://user-images.githubusercontent.com/71185156/187983247-a9b3687f-e0ea-4a54-9766-072f7f2538b7.png">

I get this error when I try to make the NCBI databases.

**Comment by carolzhou** [comment]
Looks like something at NCBI has changed. Try using ftp by hand and see if
the files are in the expected location. You can download them by hand
through an ftp connection if they have been moved. At the moment I have no
computer at hand, in the middle of a remote forest.

**Comment by lexikazen** [comment]
I wasn't able to find the files, but perhaps I'm looking in the wrong spot? I can't find anything about viral proteins in the ftp folders.

I'm not in any rush, so I can wait until you are back at a computer if needed.
________________________________

**Comment by carolzhou** [comment]
NCBI has removed from their ftp site the files containing virus genomes and virus proteins. The files have been placed behind a web interface, here:  https://www.ncbi.nlm.nih.gov/labs/virus/vssi/#/virus?SeqType_s=Nucleotide&SourceDB_s=RefSeq. The files can be downloaded by hand by following the prompts. Press the "Download" button, then select "Nucleotide" under "Sequence Data (FASTA format)", and "Next". Then, "Download All Records" and "Next". The file will download as "sequences.fasta.download". Rename the file as, "ncbiVirusGenomes.fasta". Then do the same for the protein records:  "Protein" ... rename as "ncbiVirusProteins.faa". Place the database files in your multiPhATE2 Database subdirectories as usual. 

Note that, for me, I was able to download the genome sequences (ie, Nucleotide) via the ncbi website, but the process is hanging for the protein sequences. I don't know why it's hanging, but it is. Also, I don't currently have a way of downloading these sequences in an automated fashion and capturing that in code. It is cumbersome to download by hand, but it looks as though NCBI is no longer offering the data via direct ftp.

Give that a try and let me know if it works for you.

**Comment by carolzhou** [comment]
UPDATE:  NCBI is now enabling download of their virus genome databases at:  https://ftp.ncbi.nlm.nih.gov/refseq/release/viral/
