### ISSUE TITLE
ERROR: Cannot verify blast database 

### ISSUE THREAD

**Issue by carmennns2** [carolzhou/multiPhATE2#42]
Hi, 

I am a new used to multiPhATE2. 

I corrected the configuration file as suggested under TL;DR. 

However, I keep receiving this error when running multiphate:
`python3 multiPhate.py genome1.multiPhate.config `
multiPhate says, ERROR: Cannot verify blast database for  /scratch/hdd2/carmen/Metagenomics_16S/Phage/phage_annotation/multiPhATE2/Databases/pVOGs  Please check your configuration file and Databases/ directory.

This is the config file line:
phantome_database_path='/scratch/hdd2/carmen/Metagenomics_16S/Phage/phage_annotation/multiPhATE2/Databases/Phantome' 
pvogs_database_path='/scratch/hdd2/carmen/Metagenomics_16S/Phage/phage_annotation/multiPhATE2/Databases/pVOGs'

The absolute paths for both the pathome and pvog databases are correct, however, I still get the error.

![image](https://user-images.githubusercontent.com/81758375/193056855-092d94c4-fba9-4128-9f49-f8bc9b287f86.png)

Do you have any suggestions on how to fix this issue?

Thank you so much!
Carmen

**Comment by carolzhou** [comment]
Be sure to include the filename in the path.

**Comment by carmennns2** [comment]
Yes, silly mistake (:

Thanks!

**Comment by carmennns2** [comment]
Hi Carol, 

I have another question. I am not sure how to interpret the output. I think I am missing some files. 

For example, in the main output directory (PipelineOutput), while I do have output directories for each genome processed, I do not have the CGP_RESULTS or GENOMICS_RESULTS directory (image below). 

![image](https://user-images.githubusercontent.com/81758375/199241614-621e79c9-71b3-4df7-bd52-547dbec0ab90.png)

These are the contents inside each genome output directory inside PipelineOutput. 
![image](https://user-images.githubusercontent.com/81758375/199241668-4a766dee-10ac-41dd-ba62-6eebb261b4f2.png)

I am not sure how to proceed from here. 

Thank you.

All the best,
Carmen

**Comment by carolzhou** [comment]
Please send or post your configuration file.

**Comment by carmennns2** [comment]
Hi Carol,

[genome1.multiPhate.config.txt](https://github.com/carolzhou/multiPhATE2/files/9927137/genome1.multiPhate.config.txt)
This is my config file (with an added .txt extension to make it uploadable here). 

Thank you! 
Carmen

**Comment by carolzhou** [comment]
CGP needs to be set to 'true'

**Comment by carolzhou** [comment]
If the PhATE annotation ran correctly and you have the expected output, then you do not need to repeat these calculations before running CGP and the Genomic module. You may set a checkpoint so that the MultiPhATE2 pipeline begins calculations at CGP. See the README and Wiki pages for how to do that.
