### ISSUE TITLE
pVOGs database incomplete

### ISSUE THREAD

**Issue by linsalrob** [carolzhou/multiPhATE2#9]
The pVOGs database [provided in the repo](https://github.com/carolzhou/multiPhATE2/tree/master/Databases/pVOGs) is incomplete. Currently it only has 
   - pVOGs.faa.phr
   - pVOGs.faa.pin
   - pVOGs.faa.psq

and the fasta file is not present.

**Comment by carolzhou** [comment]
Good catch. The pVOGs.faa file is now included in the Databases/pVOGs/ folder.
